{
 "title": "ACP Foundation - Overall Ethos Prod Usage",
 "tags": [
  "ACP",
  "Capacity",
  "Preprod"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Number Of Contaiers Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "count(container_spec_cpu_shares{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}) + count(container_spec_cpu_shares{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"})",
     "legendFormat": "Running Containers ",
     "limit": 5
    }
   ]
  },
  {
   "title": "Number Of Contaiers Running / Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "count(container_spec_cpu_shares{cluster=~'.*va7',arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}) or count(container_spec_cpu_shares{cluster=~\".*va7\",adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}) by (cluster)",
     "legendFormat": "{{cluster}}",
     "limit": 5
    }
   ]
  },
  {
   "title": "CPU Reservation - PreProd Clusters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "sum(container_spec_cpu_shares{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}/1024) + sum(container_spec_cpu_shares{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}/1024)",
     "legendFormat": "Reserved Cores ( provisioned ) ",
     "limit": 5
    }
   ]
  },
  {
   "title": "Memory Reservation - PreProd Clusters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "sum(container_spec_memory_limit_bytes{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}/1024/1024) + sum(container_spec_memory_limit_bytes{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}/1024/1024)",
     "legendFormat": "Reserved Memory ( Provisioned ) ",
     "limit": 5
    }
   ]
  },
  {
   "title": "ThroughPut Aggregation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "sum(rate(container_network_transmit_bytes_total{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}[2m])) + sum(rate(container_network_transmit_bytes_total{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}[2m]))",
     "legendFormat": "Tx Aggregated",
     "limit": 5
    },
    {
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "minute",
     "expr": "sum(rate(container_network_receive_bytes_total{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}[2m])) + sum(rate(container_network_receive_bytes_total{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}[2m]))",
     "legendFormat": "Rx Aggregated",
     "limit": 5
    }
   ]
  },
  {
   "title": "ACP Query for Running Applications",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{adobe_owner=~\"Proton|Platform SRE|proton|imahmed|ddg\"}/1024) by (application,cluster,adobe_owner)",
     "legendFormat": "{{application}} {{cluster}}"
    },
    {
     "expr": "sum(container_spec_cpu_shares{arch_path=~\"MC.ddg.*|EC.Worker.ConnectorsObserver|EC.AppServer.ConnectorsREST|MC.Worker.BulkIngestion|MC.Worker.*|EC.Worker.AEPSaltstack|MC.AppServer.ComputeGateway|MC.Worker.StatusScheduler\"}/1024) by (application,cluster)",
     "legendFormat": "{{application}} {{cluster}}"
    }
   ]
  }
 ]
}